### ISSUE TITLE
_

### ISSUE THREAD

**Issue by serafdev** [surprisetalk/wigwams#7]
I'm amazed about your website https://taylor.town/, confusing but great, thank you

**Comment by surprisetalk** [comment]
Thanks!

**Comment by serafdev** [comment]
No prob but my issue ain't solved yet, can we reopen

**Comment by surprisetalk** [comment]
haha sure what's the issue

**Comment by serafdev** [comment]
If you give a Human one mountain of gold, he will want two, there is no way to be satisfied on earth and that is why we keep creating fictional, and frankly non-useful, goals and dreams.

But that was only until I stumbled upon this verse: https://quran.com/3/185, describing this world exactly how I see it, and honestly I think that's how you also see it from reading your posts, quoting the end of the verse:

> [...] the life of this world is no more than the delusion of enjoyment.

Ok, my issue's solved we can close this ticket; After you gave the Qu'ran a read you can open an issue on my dotfiles and we can discuss about it.

Man this is more interesting than facebook

**Comment by surprisetalk** [comment]
Thank you for the kind words. Enjoy your week
